services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: chatbot-dashboard-backend
    restart: unless-stopped
    environment:
      - PORT=${PORT:-3000}
      - CONVERSATIONS_DIR=${CONVERSATIONS_DIR:-/app/conversations}
      - WS_PORT=${WS_PORT:-3001}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - CORS_ORIGIN=${CORS_ORIGIN:-http://frontend}
      - NODE_ENV=${NODE_ENV:-production}
    volumes:
      - ${CONVERSATIONS_PATH:-./conversations}:${CONVERSATIONS_DIR:-/app/conversations}:ro
      - ${LOGS_PATH:-./logs}:/app/logs
    # No port exposed to host - only accessible within Docker network
    networks:
      - chatbot-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: chatbot-dashboard-frontend
    restart: unless-stopped
    environment:
      - BACKEND_URL=http://backend:3000
    ports:
      - "${WEB_PORT:-80}:80"  # Only expose the web port
    depends_on:
      - backend
    networks:
      - chatbot-network

networks:
  chatbot-network:
    driver: bridge